server.port=8080

jwt.secret=your_jwt_secret_key_here_replace_in_prod
jwt.expiration=28800000

firebase.config.path=classpath:firebase-service-account.json
websocket.allowed.origins=*

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
